services:
  postgres:
    image: postgres:15-alpine
    container_name: astro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: art
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: art
      DB_NAME: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  astra-backend:
    build:
      context: ./astro_service
      dockerfile: Dockerfile
    container_name: backend-astra
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
